resume:
load_generator_only: 
load_encoder_only: 
device: cuda:0
image_size: 224
K: 1 # temporal sequence length

train:
  lr: 2e-4
  num_epochs: 50
  batch_size: 10
  num_workers: 8
  log_path: logs
  exp_name: 
  log_losses_every: 10
  visualize_every: 50
  mask_ratio: 0.005
  mask_dilation_radius: 5
  save_every: 1
  use_wandb: False
  Ke: 4 # number of repeated frames for 2nd path
  samples_per_epoch: 50000
  use_base_model_for_regularization: True
  resume_epoch: 0
  train_scale_min: 1.2
  train_scale_max: 1.8
  test_scale: 1.6

  loss_weights:
    landmark_loss: 100.0
    perceptual_loss: 10.0
    reconstruction_loss: 10.0
    lipreading_loss: 0.0
    emotion_loss: 1.0
    jaw_regularization: 1e-2
    expression_regularization: 1e-3
    shape_regularization: 100
    cycle_loss: 1.0
    identity_loss: .1
    mica_loss: 0
    deca_loss: 0

arch:
  backbone_pose: mobilenet
  backbone_shape: mobilenet
  backbone_expression: mobilenet
  num_expression: 50
  num_shape: 300
  optimize_pose: False
  optimize_shape: False
  render_face_only: True
  use_eyelids: True
  use_expression_templates_in_second_path: True
  freeze_generator_in_second_path: False

render:
  full_head: False
  extended: False
  eyes: False
  different_color_extended: False

dataset:
  LRS3_path: LRS3
  LRS3_landmarks_path: LRS3_landmarks
  MEAD_path: MEAD_preprocessed/videos/
  MEAD_landmarks_path: MEAD_landmarks
  FFHQ_path: FFHQ256/ffhq256
  FFHQ_fan_landmarks_path: FFHQ256/fan_landmarks_hhj1897
  FFHQ_mediapipe_landmarks_path: FFHQ256/mediapipe_landmarks
  CelebA_path: CelebA/img_align_celeba
  CelebA_fan_landmarks_path: CelebA/fan_landmarks_hhj1897
  CelebA_mediapipe_landmarks_path: CelebA/mediapipe_landmarks
  MEAD_sides_path: MEAD_preprocessed


  LRS3_percentage: 0.2 #0.2
  LRS3_temporal_sampling: False
  MEAD_percentage: 0.2 #0.2
  FFHQ_percentage: 0.2 #0.3
  CelebA_percentage: 0.2 #0.2
  MEAD_sides_percentage: 0.2 #0.1


